=== Coverli/otherCL/XML DTD/demo/html.dtd
<!ELEMENT body (h1,p,div,form,table,br)*>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT div (#PCDATA)>
<!ELEMENT form (input)*>
<!ELEMENT input (#PCDATA)>
<!ELEMENT table (th,tr)*>
<!ELEMENT th (td)*>
<!ELEMENT tr (td)*>
<!ELEMENT td (#PCDATA)>
<!ELEMENT br EMPTY>

<!ATTLIST div id CDATA #REQUIRED>
<!ATTLIST div class CDATA #IMPLIED>
<!ATTLIST div name CDATA #IMPLIED>
<!ATTLIST form method (post|get) #REQUIRED>
<!ATTLIST input type (button|checkbox|color|date|submit) #REQUIRED>
<!ATTLIST input value CDATA #REQUIRED>
<!ATTLIST table class CDATA #IMPLIED>

=== Coverli/otherCL/XML DTD/demo/html.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE body SYSTEM "html.dtd">
<body>
    <h1>一号标题</h1>
    <p>段落</p>
    <div id="" class="" name=""></div>
    <form method="post">
        <input type="button" value=""/>
        <input type="checkbox" value=""/>
        <input type="color" value=""/>
        <input type="date" value=""/>
        <input type="submit" value=""/>
    </form>
    <table class="">
        <th>
            <td></td>
        </th>
        <tr>
            <td></td>
        </tr>
    </table>
    <br/>
</body>
